### PR TITLE
Updated to swift 4.2

### PR DESCRIPTION
**Pull request by kajensen**

### CODE REVIEW

**Comment by mknippen** [comment]
+1. Please merge!!

**Comment by mknippen** [comment]
@kajensen You should also update and change the .swift_version file to 4.2 if possible.

**Comment by ErAbhishekChandani** [comment]
Will check this asap.

**Comment by mknippen** [comment]
Great, thank you!

**Comment by nicoonswift** [comment]
Hello, any chance we can have the PR merged in the short term ? I'm currently dealing with needing to update this dependency on a project, as it runs on [Swift 3.0](https://github.com/ErAbhishekChandani/ACProgressHUD/blob/master/.swift-version) which is a version [no longer supported](https://developer.apple.com/documentation/xcode_release_notes/xcode_10_2_release_notes/swift_5_release_notes_for_xcode_10_2?preferredLanguage=occ) in Xcode 10.2. Thanks in advance !

**Comment by ErAbhishekChandani** [comment]
Sure I will check

**Comment by ErAbhishekChandani** [comment]
Updated to swift 5.

**Pull request closed without merging**
